// Shareable PDF reports, generated fully offline with jsPDF. Two shapes: a single dated readings
// table, and the whole progress comparison (position × every attempt, one grid per metric). Shared
// through the native share sheet where the browser supports sharing files; otherwise downloaded.

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import type { ReadingsTable, Watch, Position } from "@/types";
import { POSITIONS } from "@/types";

const MARGIN = 14;

function addHeader(doc: jsPDF, watchName: string, refNumber: string, subtitle: string): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("ChronoGrapher — Regulation Report", MARGIN, 18);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(`Watch: ${watchName || "Untitled watch"}`, MARGIN, 27);
  doc.text(`Reference: ${refNumber || "N/A"}`, MARGIN, 33);
  doc.setTextColor(110);
  doc.setFontSize(10);
  doc.text(subtitle, MARGIN, 39);
  doc.setTextColor(0);
  return 45; // y where content starts
}

function addFooter(doc: jsPDF): void {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by ChronoGrapher · ${format(new Date(), "PPp")}`,
      MARGIN,
      doc.internal.pageSize.getHeight() - 8,
    );
    doc.setTextColor(0);
  }
}

export function buildTablePdf(watchName: string, refNumber: string, table: ReadingsTable): jsPDF {
  const doc = new jsPDF();
  const startY = addHeader(doc, watchName, refNumber, `Readings taken ${format(new Date(table.createdAt), "PPp")}`);
  autoTable(doc, {
    startY,
    margin: { left: MARGIN, right: MARGIN },
    head: [["Position", "Rate (s/d)", "Amp (°)", "Beat Error (ms)", "Lift Angle (°)"]],
    body: table.readings.map((r) => [r.position, r.rate, r.amplitude, r.beatError, r.liftAngle]),
    styles: { fontSize: 10 },
    headStyles: { fillColor: [40, 40, 46] },
  });
  addFooter(doc);
  return doc;
}

const METRICS = [
  { key: "rate", label: "Rate (s/d)" },
  { key: "amplitude", label: "Amplitude (°)" },
  { key: "beatError", label: "Beat Error (ms)" },
] as const;

export function buildComparisonPdf(watch: Watch): jsPDF {
  const doc = new jsPDF();
  // Oldest → newest so progress reads left-to-right, matching the on-screen comparison.
  const tables = [...watch.tables].reverse();
  const positions = POSITIONS.filter((p) => tables.some((t) => t.readings.some((r) => r.position === p)));
  const columnHead = ["Position", ...tables.map((t, i) => `#${i + 1}\n${format(new Date(t.createdAt), "d MMM HH:mm")}`)];
  const valueAt = (t: (typeof tables)[number], pos: Position, key: (typeof METRICS)[number]["key"]) =>
    t.readings.find((r) => r.position === pos)?.[key] ?? "—";

  let y = addHeader(
    doc,
    watch.name,
    watch.refNumber,
    `Progress across ${tables.length} attempts — oldest on the left`,
  );
  for (const metric of METRICS) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(metric.label, MARGIN, y + 6);
    autoTable(doc, {
      startY: y + 9,
      margin: { left: MARGIN, right: MARGIN },
      head: [columnHead],
      body: positions.map((pos) => [pos, ...tables.map((t) => valueAt(t, pos, metric.key))]),
      styles: { fontSize: 9 },
      headStyles: { fillColor: [40, 40, 46] },
    });
    y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
    if (y > doc.internal.pageSize.getHeight() - 60 && metric !== METRICS[METRICS.length - 1]) {
      doc.addPage();
      y = 15;
    }
  }
  addFooter(doc);
  return doc;
}

// Share the PDF via the native share sheet where possible, else download it.
// Returns "shared" | "downloaded" so the caller can word its toast.
export async function sharePdf(doc: jsPDF, filename: string, title: string): Promise<"shared" | "downloaded"> {
  const blob = doc.output("blob");
  const file = new File([blob], filename, { type: "application/pdf" });
  if (navigator.canShare?.({ files: [file] })) {
    try {
      await navigator.share({ files: [file], title });
      return "shared";
    } catch (e) {
      if ((e as Error).name === "AbortError") return "shared"; // user closed the sheet — not an error
      // fall through to download on any real share failure
    }
  }
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
  return "downloaded";
}

export function reportFilename(watchName: string, kind: "readings" | "comparison"): string {
  const slug = (watchName || "watch").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 40) || "watch";
  return `chronographer-${slug}-${kind}-${format(new Date(), "yyyy-MM-dd")}.pdf`;
}
