// @ts-nocheck
// This file is autogenerated by Firebase Studio. Do not edit manually.

// To change this configuration, update the FIREBASE_PROJECT_ID
// in your project's .env file and then re-run the 'getFirebaseConfig'
// genkit flow.
import { initializeApp, getApp, getApps } from "firebase/app";
import { getFirestore, connectFirestoreEmulator } from "firebase/firestore";
import { getAuth, connectAuthEmulator } from "firebase/auth";

const firebaseConfig = {
  "projectId": "studio-329968613-80cee",
  "appId": "1:984535644820:web:ce0a47475d13e8f9449281",
  "apiKey": "AIzaSyCpurcATJIitkRdnOPrejWyekQ5CTPiNJ0",
  "authDomain": "studio-329968613-80cee.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "984535644820"
};

function initializeFirebase() {
    const app = getApps().length ? getApp() : initializeApp(firebaseConfig);
    const firestore = getFirestore(app);
    const auth = getAuth(app);

    return { app, firestore, auth };
}

export { initializeFirebase, firebaseConfig };
